### ISSUE TITLE
Website does not load in TOR browser

### ISSUE THREAD

**Issue by Karmel0x** [mesh0000/poolui#36]
Issue #9

Same problem on TOR browser
Empty / blank page when visiting https://xmrpool.net/ or https://monero.hashvault.pro/

`User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0`

**Comment by ephz3nt** [comment]
tor is disabled javascript, you can enabled and try again

**Comment by Karmel0x** [comment]
Of course i have enabled javascript... It's working for you ?

**Comment by Karmel0x** [comment]
Works in the new Tor version cause Firefox has been updated

`Tor Browser 8.0a9 -- June 27 2018`
`- * Update Firefox to 60.1.0esr`

**Comment by Karmel0x** [comment]
Works in the new version of Tor cause Firefox has been updated.
